### ISSUE TITLE
buildがこける

### ISSUE THREAD

**Issue by yupix** [TeamBlackCrystal/ayuskey-fluorite#11]
最新のコミットである 63cc5f1fa0c871a7f4a0a1238e4aae8358e999cd でciがこけてたから一応ciが成功してる 19d632e41f10d0d090ddceca5ef94fc890a37509 をローカルにおいてbuildしてみたけど、なんかこける気がする

**Comment by yupix** [comment]
devは動く

**Comment by sousuke0422** [comment]
buildコケるのは現状仕様

**Comment by sousuke0422** [comment]
ciは暫定処置 6db9948fd6ff0d975cd9ba6af8f445b760072190

**Comment by sousuke0422** [comment]
いらない
